apiVersion: v1
kind: ReplicationController
metadata:
  name: dolphago
  labels:
    run: dolphago
spec:
  replicas: 1
  selector:
    run: dolphago
  template:
    metadata:
      labels:
        run: dolphago
    spec:
      containers:
      - name: dolphago
        image: adamdoha/dolphago:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      
