apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubia
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubia
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 30